package generator

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// API generates a JSON API controller and resource for a model.
func API(appPath, name string, fields map[string]string) error {
	data := buildResourceData(appPath, name, fields)
	plural := data.Plural
	singular := data.Singular
	title := data.Title

	ctrlDir := filepath.Join(appPath, "app", "controllers")
	resDir := filepath.Join(appPath, "app", "resources")
	os.MkdirAll(resDir, 0755)

	ctrlPath := filepath.Join(ctrlDir, plural+"_api_controller.go")
	resPath := filepath.Join(resDir, singular+"_resource.go")

	ctrlTmpl := `package controllers

import (
	"net/http"
	"strconv"

	"{{.Module}}/app/models"
	"{{.Module}}/app/resources"
	"github.com/lsgser/gofreight/api"
	"github.com/lsgser/gofreight/controller"
)

type {{.Name}}APIController struct{ controller.Base }

func (c *{{.Name}}APIController) Index(base controller.Base) error {
	items, err := models.{{.Plural}}.Query(base.Request.Context()).Get()
	if err != nil {
		return err
	}
	var res []api.Resource
	for _, item := range items {
		res = append(res, resources.New{{.Name}}Resource(item))
	}
	api.RenderMany(base.Response, http.StatusOK, res)
	return nil
}

func (c *{{.Name}}APIController) Show(base controller.Base) error {
	id, _ := strconv.ParseInt(base.Param("id"), 10, 64)
	item, err := models.{{.Plural}}.Find(base.Request.Context(), id)
	if err != nil {
		base.NotFound("{{.Singular}} not found")
		return nil
	}
	api.Render(base.Response, http.StatusOK, resources.New{{.Name}}Resource(*item))
	return nil
}
`

	resTmpl := `package resources

import (
	"{{.Module}}/app/models"
	"github.com/lsgser/gofreight/api"
)

type {{.Name}}Resource struct {
	Item models.{{.Name}}
}

func New{{.Name}}Resource(item models.{{.Name}}) api.Resource {
	return {{.Name}}Resource{Item: item}
}

func (r {{.Name}}Resource) ToMap() map[string]any {
	return map[string]any{
		"id": r.Item.ID,
	}
}
`

	if err := writeTemplate(ctrlPath, ctrlTmpl, data); err != nil {
		return err
	}
	if err := writeTemplate(resPath, resTmpl, data); err != nil {
		return err
	}

	snippet := fmt.Sprintf(`/*
|--------------------------------------------------------------------------
| API Routes
|--------------------------------------------------------------------------
|
| Add to routes/api.go:
|
|   api := r.Group(api.VersionPrefix("v1"))
|   api.Get("/%s", controller.Handler((&controllers.%sAPIController{}).Index))
|   api.Get("/%s/:id", controller.Handler((&controllers.%sAPIController{}).Show))
|
*/
`, plural, title, plural, title)
	snippetPath := filepath.Join(appPath, "config", "api_routes_"+plural+".txt")
	return os.WriteFile(snippetPath, []byte(snippet), 0644)
}

// BlueprintMigration generates up/down SQL from a blueprint callback name.
func BlueprintMigration(appPath, name, table string, alter bool) error {
	var up, down string
	if alter {
		up, down = alterPlaceholder(table)
	} else {
		up, down = createPlaceholder(table)
	}
	dir := filepath.Join(appPath, "db", "migrate")
	version := strings.ReplaceAll(name, " ", "_")
	return writeMigrationPair(dir, version, up, down)
}

func createPlaceholder(table string) (string, string) {
	return fmt.Sprintf("-- Edit with database.CreateTableBlueprint(%q, func(b *database.Blueprint) { ... })", table),
		fmt.Sprintf("DROP TABLE IF EXISTS %s;", table)
}

func alterPlaceholder(table string) (string, string) {
	return fmt.Sprintf("-- Edit with database.AlterTableBlueprint(%q, func(b *database.Blueprint) { ... })", table),
		"-- down SQL auto-generated by AlterTableBlueprint"
}

func writeMigrationPair(dir, version, up, down string) error {
	os.MkdirAll(dir, 0755)
	ts := version
	upPath := filepath.Join(dir, ts+".sql")
	downPath := filepath.Join(dir, ts+"_down.sql")
	if err := os.WriteFile(upPath, []byte(up), 0644); err != nil {
		return err
	}
	return os.WriteFile(downPath, []byte(down), 0644)
}
