-- --------------------------------------------------------------------------
-- README
-- --------------------------------------------------------------------------
--
-- Database migration defining schema changes applied in order by gofreight
-- migrate.
--
-- Pair up/down migrations when altering columns; prefer blueprint Go
-- migrations for new projects.
--
-- --------------------------------------------------------------------------
-- README
-- --------------------------------------------------------------------------
--
-- Database migration or schema SQL for versioned database changes.
--
-- --------------------------------------------------------------------------
-- Database Seed Files (SQL)
-- --------------------------------------------------------------------------
--
-- Place .sql files in this directory. They run in alphabetical order when
-- you execute:
--
--   gofreight db:seed
--
-- For Go-based seeders, use db/seeders/ and gofreight make:seeder.
--
